yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'),
    path(
        'group/<slug:slug>/',
        views.group_post,
        name='group_list'),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'),
    path(
        'create/',
        views.post_create,
        name='post_create'),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Комментарий:',
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments',
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta():
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follows'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .utils import paginator_view
from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    page_obj = paginator_view(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_post(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginator_view(post_list, request)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginator_view(post_list, request)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author__username=username).exists()
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    com_form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': comments,
        'com_form': com_form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    return render(request, 'posts/create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_view(post_list, request)
    following = Follow.objects.filter(
        user=request.user).exists()
    context = {
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create.html
{% extends 'base.html' %}
{% block title %}
    {% if is_edit %}
        Редактировать пост
    {% else %}
        Новый пост
    {% endif %}
{% endblock %}
{% block content %}
    <main>
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-md-8 p-5">
                    <div class="card">
                        <div class="card-header">
                            {% if is_edit %}
                                Редактировать пост
                            {% else %}
                                Новый пост
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <form method="post"
                                  enctype="multipart/form-data"
                                    {% if is_edit %}
                                  action='{% url 'posts:post_edit' post.id %}'
                                    {% else %}
                                  action='{% url 'posts:post_create' %}'
                                    {% endif %}>
                                {% csrf_token %}
                                <div class="form-group row my-3 p-3">
                                    {{ form.as_p }}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <div class="alert alert-danger">
                                                {{ error|escape }}
                                            </div>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                        <div class="alert alert-danger">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="d-flex justify-content-end">
                                    <button type="submit" class="btn btn-primary">
                                        {% if is_edit %}
                                            Сохранить
                                        {% else %}
                                            Добавить
                                        {% endif %}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Последние обновления на сайте
{% endblock %}
{% block content %}
    {% include 'includes/switcher.html' %}
    {% if following %}
        <h1>Подписки</h1>
    {% else %}
        <h1>Вы не на кого не подписаны.</h1>
    {% endif %}
    {% for post in page_obj %}
        <article>
            <ul>
                <li> Группа: {{ post.group.title }}</li>
                <li>
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
                {{ post.text|linebreaksbr }}
            </p>
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        </article>
    {% endfor %}
    {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <h1> {{ group.title }}</h1>
  <p>{{ group.description }} </p>
  {% for post in page_obj %}
    <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text|linebreaksbr }}
    </p>
    {% if not forloop.last %}
      <hr>
    {% endif %}
    </article>
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
    {% include 'includes/switcher.html' %}
  <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      <article>
      <ul>
        <li> Группа: {{ post.group.title }}</li>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
      </article>
    {% endfor %}
    {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
    {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
    {% load sorl_thumbnail %}
    <main>
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Дата публикации: {{ post.pub_date }}
                    </li>
                    {% if post.group %}
                        <li class="list-group-item">
                            Группа: {{ post.group.title }}
                            <a href="{% url 'posts:group_list' post.group.slug %}">
                                все записи группы
                            </a>
                        </li>
                    {% endif %}
                    <li class="list-group-item">
                        Автор: {{ post.author.get_full_name }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора: <span>{{ post.author.posts.count }}</span>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:profile' post.author.username %}">
                            все посты пользователя
                        </a>
                    </li>
                </ul>
            </aside>
            <article class="col-12 col-md-9">
                <p>
                    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                        <img class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}
                </p>
                <p>
                    {{ post.text|linebreaksbr }}
                </p>
                {% if post.author == user %}
                    <a type="button" class="btn btn-outline-danger"
                       href="{% url 'posts:post_edit' post.id %}">
                        Редактировать запись
                    </a>
                {% endif %}
                {% include 'includes/comment.html' %}
            </article>
        </div>
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
    <main>
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if author.username != user.username %}
            {% if following %}
            <a class="btn btn-lg btn-light"
               href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
                Отписаться
            </a>
            {% else %}
            <a class="btn btn-lg btn-primary"
               href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
                Подписаться
            </a>
            {% endif %}
        {% endif %}
        {% for post in page_obj %}
            <article>
                <ul>
                    <li>
                        Автор: {{ post.author.get_full_name }}
                        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>
                    {{ post.text|linebreaksbr }}
                </p>
                <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
            </article>
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы </a>
            {% endif %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </main>
{% endblock %}